<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\OpeaLibrary.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\OpeaLibrary.Infrastructure.csproj" />
    <ProjectReference Include="..\Application\OpeaLibrary.Application.csproj" />
  </ItemGroup>

  

</Project>
