global using AutoMapper;
global using FluentValidation;
global using MediatR;
global using OpeaLibrary.Application.Books.Queries.GetAllBooks;
global using OpeaLibrary.Application.Books.Queries.GetBookById;
global using OpeaLibrary.Application.Loans.Queries.GetAllLoans;
global using OpeaLibrary.Domain.Entities;
global using OpeaLibrary.Domain.Enums;
global using OpeaLibrary.Domain.Interfaces;
