services:
  db_save:
    image: postgres:15.3-alpine
    container_name: db_save
    restart: always
    environment:
      POSTGRES_USER: ${DB_WRITE_USER}
      POSTGRES_PASSWORD: ${DB_WRITE_PASSWORD}
      POSTGRES_DB: ${DB_WRITE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_save_data:/var/lib/postgresql/data
    networks:
      - db_network

  db_read:
    image: mongo
    restart: always
    container_name: db_read
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_READ_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_READ_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db_read_data:/data/db
    networks:
      - db_network

networks:
  db_network:
    driver: bridge  
  
volumes:
  db_save_data:
  db_read_data: